version: '3'
services:
  streamarrfs:
    build:
      context: .
      dockerfile: ./docker/build.Dockerfile
      target: prod
    ports:
      - 3000:3000
    environment:
      - STREAMARR_DB_PATH=/db/streamarr.sqlite
      - NODE_ENV=production
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./db:/db
      - ./downloads:/downloads
      - ./mnt:/tmp:shared
    command: npm run start:prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  streamarrtest:
    build:
      context: .
      dockerfile: ./docker/build.Dockerfile
      target: test
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    command: npm run test