version: '3'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    depends_on:
      - fuse
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32470:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32416:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Melbourne/Australia
      - VERSION=docker
      - PLEX_CLAIM=claim-xxxxxxxxxxxxxxxxxxxx
      - ADVERTISE_IP="http://localhost:32400/"
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./mnt:/streamarfs:shared

networks:
  streamarr_net: