version: '3'
services:
  plex:
    image: plexinc/pms-docker
    network_mode: host
    restart: always
    depends_on:
      streamarrfs:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "ls", "-d", "/streamarrfs/healthcheck"]
      interval: 30s
      timeout: 10s
      start_period: 5s
    volumes:
        - streamarrfs-plex-config:/config
        - streamarrfs-plex-transcode:/transcode
        - /tmp/streamarrfstmp/streamarrfs:/streamarrfs:ro
    #environment:
        #TZ: 'Australia/Melbourne'
        #PLEX_CLAIM: 'claim-XXXXXjaNF4Y7CW5Agy9'
        #ALLOWED_NETWORKS: '10.0.0.0/24'
    logging:
        driver: json-file
        options:
            max-size: 10m

  streamarrfs:
    image: puttyman/streamarrfs:master
    network_mode: host
    environment:
      - NODE_ENV=production
      - STREAMARRFS_WEBTORRENT_DOWNLOAD_PATH=/downloads
      - STREAMARRFS_MOUNT_PATH=/tmp/streamarrfs
      - STREAMARRFS_FUSE_AUTO_UNMOUNT=true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor=unconfined
    volumes:
      - streamarrfs-db:/server/db
      - streamarrfs-downloads:/downloads
      - /tmp/streamarrfs-tmp:/tmp:shared
    healthcheck:
      test: ["CMD", "ls", "-d", "/tmp/streamarrfs/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      # Note only resouces is allowed by docker compose. Others are ignored
      resources:
        limits:
          memory: 8196M
        reservations:
          memory: 2048M

volumes:
  streamarrfs-plex-config:
  streamarrfs-plex-transcode:
  streamarrfs-downloads:
  streamarrfs-db: